model: yolov8s.pt
task: detect  # YOLO task, i.e. detect, segment, classify, pose
mode: predict  # YOLO mode, i.e. train, val, predict, export, track, benchmark

# Prediction settings --------------------------------------------------------------------------------------------------
conf: 0.6  # object confidence threshold for detection (default 0.25 predict, 0.001 val)
iou: 0.7  # intersection over union (IoU) threshold for NMS
max_det: 300  # maximum number of detections per image
half: False  # use half precision (FP16)
dnn: False  # use OpenCV DNN for ONNX inference
plots: True  # save plots during train/val
source:  # source directory for images or videos
show: True  # show results if possible
save_txt: False  # save results as .txt file
save_conf: False  # save results with confidence scores
save_crop: False  # save cropped images with results
show_labels: True  # show object labels in plots
show_conf: True  # show object confidence scores in plots
vid_stride: 1  # video frame-rate stride
line_width:   # line width of the bounding boxes
visualize: True
source: '/home/jin/workspace/RealFold-AI/test/images/truck.jpg'

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # for overriding defaults.yaml